# Generated by Django 5.1.5 on 2025-01-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_sms_email_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sms_email_notif',
        ),
    ]
