# Generated by Django 5.1.5 on 2025-01-30 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_sms_email_notif'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('org_description', models.TextField(blank=True, null=True)),
                ('estd_date', models.DateField(verbose_name='Established Date')),
                ('website_url', models.TextField(blank=True, max_length=122, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisation_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
