# Generated by Django 5.1.5 on 2025-02-04 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseekerprofile_educationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='experience_years',
            field=models.SmallIntegerField(default=0, help_text='default value will be 0'),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime'), ('ContractBased', 'ContractBased'), ('Intern', 'Intern'), ('FreeLancer', 'FreeLancer')], max_length=25)),
                ('job_category', models.CharField(choices=[('Teaching', 'Teaching'), ('NonTeaching', 'NonTeaching'), ('Administrative', 'Administrative')], max_length=25)),
                ('job_title', models.CharField(help_text='Title for the job', max_length=120)),
                ('job_description', models.TextField(help_text='description about required job')),
                ('job_city', models.CharField(help_text='city of company', max_length=122)),
                ('job_state', models.CharField(help_text='state of company', max_length=122)),
                ('job_full_address', models.CharField(help_text='Full address of company', max_length=122)),
                ('job_address_pin', models.CharField(help_text='pin number of the address', max_length=110)),
                ('job_mobile', models.SmallIntegerField(blank=True, null=True)),
                ('job_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_is_remote', models.BooleanField(default=False)),
                ('job_experience_required', models.SmallIntegerField(default=0)),
                ('job_salary_offered', models.CharField(help_text='offered salary range')),
                ('job_skills', models.TextField(help_text='skills required for the job')),
                ('job_logo', models.FileField(blank=True, null=True, upload_to='job_logo/')),
                ('job_expiration_date', models.DateField(blank=True, help_text='after this date job will be removed from the portal', null=True)),
                ('total_application', models.PositiveIntegerField(default=0, help_text='Total number of applications')),
                ('is_active', models.BooleanField(default=True, help_text='Is this job posting active?')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this job featured?')),
                ('is_verified', models.BooleanField(default=False, help_text='Has this job been verified by admin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
