# Generated by Django 5.1.5 on 2025-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_jobposting_job_logo_jobposting_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_mobile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
