# Generated by Django 5.1.5 on 2025-02-04 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_jobposting_job_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationregister',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='organisation_images/'),
            preserve_default=False,
        ),
    ]
