# Generated by Django 5.1.5 on 2025-02-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_jobseekerprofile_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='optional cover letter provided by the applicant', null=True)),
                ('resume', models.FileField(blank=True, help_text='Optional resume upload; if not provided, the resume on the profile may be used.', null=True, upload_to='job_applications/resumes/')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('IN_REVIEW', 'In Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='APPLIED', help_text='The current status of the application.', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_viewed', models.BooleanField(default=False)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.jobposting')),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('job_posting', 'job_seeker_profile')},
            },
        ),
    ]
