# Generated by Django 5.1.5 on 2025-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='YOLO', max_length=200),
            preserve_default=False,
        ),
    ]
